version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  access:
    format: "%(asctime)s - %(message)s"
  uvicorn_default:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(levelprefix)s %(message)s"
    use_colors: true

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    stream: ext://sys.stdout
  uvicorn:
    class: logging.FileHandler
    formatter: default
    filename: logs/uvicorn.log
    level: DEBUG
  uvicorn_error:
    class: logging.FileHandler
    formatter: default
    filename: logs/uvicorn.error.log
    level: ERROR
  uvicorn_access:
    class: logging.FileHandler
    formatter: access
    filename: logs/uvicorn.access.log
    level: DEBUG
  ddtrace:
    class: logging.FileHandler
    formatter: default
    filename: logs/ddtrace.log
    level: DEBUG
    mode: a
    encoding: utf-8    
  sqlalchemy:
    class: logging.FileHandler
    formatter: default
    filename: logs/sqlalchemy.log
    level: DEBUG
  botocore:
    class: logging.FileHandler
    formatter: default
    filename: logs/botocore.log
    level: DEBUG
loggers:
  uvicorn:
    handlers: [console, uvicorn]
    level: DEBUG
    propagate: true
  uvicorn.access:
    handlers: [uvicorn_access]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [uvicorn_error]
    level: ERROR
    propagate: false
  ddtrace:
    handlers: [console, ddtrace]
    level: DEBUG
    propagate: false
  datadog:
    handlers: [console, ddtrace]
    level: DEBUG
    propagate: false   
  sqlalchemy:
    handlers: [sqlalchemy]
    level: DEBUG
    propagate: false
  botocore:
    handlers: [botocore]
    level: DEBUG
    propagate: false

root:
  handlers: [console, uvicorn]
  level: DEBUG    